/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace CharityVerificationSystem {
  export type CharityInfoStruct = {
    id: PromiseOrValue<BigNumberish>;
    walletAddress: PromiseOrValue<string>;
    name: PromiseOrValue<string>;
    description: PromiseOrValue<string>;
    website: PromiseOrValue<string>;
    registrationNumber: PromiseOrValue<string>;
    country: PromiseOrValue<string>;
    category: PromiseOrValue<string>;
    status: PromiseOrValue<BigNumberish>;
    verificationDate: PromiseOrValue<BigNumberish>;
    lastUpdated: PromiseOrValue<BigNumberish>;
    verifier: PromiseOrValue<string>;
    verificationDetails: PromiseOrValue<string>;
    rejectionReason: PromiseOrValue<string>;
    totalDonationsReceived: PromiseOrValue<BigNumberish>;
    totalCampaigns: PromiseOrValue<BigNumberish>;
    reputationScore: PromiseOrValue<BigNumberish>;
    isFeatured: PromiseOrValue<boolean>;
  };

  export type CharityInfoStructOutput = [
    BigNumber,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    number,
    BigNumber,
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean
  ] & {
    id: BigNumber;
    walletAddress: string;
    name: string;
    description: string;
    website: string;
    registrationNumber: string;
    country: string;
    category: string;
    status: number;
    verificationDate: BigNumber;
    lastUpdated: BigNumber;
    verifier: string;
    verificationDetails: string;
    rejectionReason: string;
    totalDonationsReceived: BigNumber;
    totalCampaigns: BigNumber;
    reputationScore: BigNumber;
    isFeatured: boolean;
  };

  export type VerificationApplicationStruct = {
    charityId: PromiseOrValue<BigNumberish>;
    applicant: PromiseOrValue<string>;
    applicationDetails: PromiseOrValue<string>;
    supportingDocuments: PromiseOrValue<string>;
    applicationDate: PromiseOrValue<BigNumberish>;
    status: PromiseOrValue<BigNumberish>;
    reviewer: PromiseOrValue<string>;
    reviewNotes: PromiseOrValue<string>;
    reviewDate: PromiseOrValue<BigNumberish>;
  };

  export type VerificationApplicationStructOutput = [
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    number,
    string,
    string,
    BigNumber
  ] & {
    charityId: BigNumber;
    applicant: string;
    applicationDetails: string;
    supportingDocuments: string;
    applicationDate: BigNumber;
    status: number;
    reviewer: string;
    reviewNotes: string;
    reviewDate: BigNumber;
  };
}

export interface CharityVerificationSystemInterface extends utils.Interface {
  functions: {
    "applicationCount()": FunctionFragment;
    "applyForVerification(uint256,string,string)": FunctionFragment;
    "charities(uint256)": FunctionFragment;
    "charityCount()": FunctionFragment;
    "charityIdByAddress(address)": FunctionFragment;
    "externalVerificationSources(string)": FunctionFragment;
    "feeRecipient()": FunctionFragment;
    "getCharitiesByCategory(string)": FunctionFragment;
    "getCharityInfo(uint256)": FunctionFragment;
    "getCharityInfoByAddress(address)": FunctionFragment;
    "getFeaturedCharities()": FunctionFragment;
    "getTotalApplications()": FunctionFragment;
    "getTotalCharities()": FunctionFragment;
    "getVerificationApplication(uint256)": FunctionFragment;
    "getVerifiedCharities()": FunctionFragment;
    "governanceToken()": FunctionFragment;
    "isCharityVerified(uint256)": FunctionFragment;
    "isCharityVerifiedByAddress(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "reactivateCharity(uint256)": FunctionFragment;
    "registerCharity(address,string,string,string,string,string,string)": FunctionFragment;
    "rejectVerification(uint256,string)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "requiredReputationForVerification()": FunctionFragment;
    "revokeVerification(uint256,string)": FunctionFragment;
    "setFeaturedStatus(uint256,bool)": FunctionFragment;
    "suspendCharity(uint256,string)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "treasury()": FunctionFragment;
    "updateExternalVerificationSource(string,bool)": FunctionFragment;
    "updateFeeRecipient(address)": FunctionFragment;
    "updateReputationScore(uint256,uint256)": FunctionFragment;
    "updateRequiredReputation(uint256)": FunctionFragment;
    "updateVerificationFee(uint256)": FunctionFragment;
    "verificationApplications(uint256)": FunctionFragment;
    "verificationDuration()": FunctionFragment;
    "verificationFee()": FunctionFragment;
    "verifyCharity(uint256,string,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "applicationCount"
      | "applyForVerification"
      | "charities"
      | "charityCount"
      | "charityIdByAddress"
      | "externalVerificationSources"
      | "feeRecipient"
      | "getCharitiesByCategory"
      | "getCharityInfo"
      | "getCharityInfoByAddress"
      | "getFeaturedCharities"
      | "getTotalApplications"
      | "getTotalCharities"
      | "getVerificationApplication"
      | "getVerifiedCharities"
      | "governanceToken"
      | "isCharityVerified"
      | "isCharityVerifiedByAddress"
      | "owner"
      | "reactivateCharity"
      | "registerCharity"
      | "rejectVerification"
      | "renounceOwnership"
      | "requiredReputationForVerification"
      | "revokeVerification"
      | "setFeaturedStatus"
      | "suspendCharity"
      | "transferOwnership"
      | "treasury"
      | "updateExternalVerificationSource"
      | "updateFeeRecipient"
      | "updateReputationScore"
      | "updateRequiredReputation"
      | "updateVerificationFee"
      | "verificationApplications"
      | "verificationDuration"
      | "verificationFee"
      | "verifyCharity"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "applicationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyForVerification",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "charities",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "charityCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "charityIdByAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "externalVerificationSources",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCharitiesByCategory",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCharityInfo",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCharityInfoByAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeaturedCharities",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalApplications",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCharities",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationApplication",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifiedCharities",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isCharityVerified",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isCharityVerifiedByAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reactivateCharity",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCharity",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectVerification",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requiredReputationForVerification",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeVerification",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeaturedStatus",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "suspendCharity",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateExternalVerificationSource",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeeRecipient",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputationScore",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRequiredReputation",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVerificationFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationApplications",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verificationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCharity",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "applicationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyForVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "charities", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "charityCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "charityIdByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "externalVerificationSources",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCharitiesByCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCharityInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCharityInfoByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeaturedCharities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCharities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationApplication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifiedCharities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCharityVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCharityVerifiedByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateCharity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCharity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredReputationForVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeaturedStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suspendCharity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateExternalVerificationSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputationScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRequiredReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVerificationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCharity",
    data: BytesLike
  ): Result;

  events: {
    "CharityFeatured(uint256,bool)": EventFragment;
    "CharityRegistered(uint256,address,string,address)": EventFragment;
    "ExternalVerificationSourceUpdated(string,bool)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RequiredReputationUpdated(uint256,uint256)": EventFragment;
    "VerificationApplied(uint256,address,uint256)": EventFragment;
    "VerificationFeeUpdated(uint256,uint256)": EventFragment;
    "VerificationStatusUpdated(uint256,uint8,uint8,address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CharityFeatured"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CharityRegistered"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ExternalVerificationSourceUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequiredReputationUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VerificationApplied"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VerificationFeeUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VerificationStatusUpdated"): EventFragment;
}

export interface CharityFeaturedEventObject {
  charityId: BigNumber;
  featured: boolean;
}
export type CharityFeaturedEvent = TypedEvent<
  [BigNumber, boolean],
  CharityFeaturedEventObject
>;

export type CharityFeaturedEventFilter = TypedEventFilter<CharityFeaturedEvent>;

export interface CharityRegisteredEventObject {
  charityId: BigNumber;
  walletAddress: string;
  name: string;
  registrar: string;
}
export type CharityRegisteredEvent = TypedEvent<
  [BigNumber, string, string, string],
  CharityRegisteredEventObject
>;

export type CharityRegisteredEventFilter =
  TypedEventFilter<CharityRegisteredEvent>;

export interface ExternalVerificationSourceUpdatedEventObject {
  source: string;
  allowed: boolean;
}
export type ExternalVerificationSourceUpdatedEvent = TypedEvent<
  [string, boolean],
  ExternalVerificationSourceUpdatedEventObject
>;

export type ExternalVerificationSourceUpdatedEventFilter =
  TypedEventFilter<ExternalVerificationSourceUpdatedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RequiredReputationUpdatedEventObject {
  oldReputation: BigNumber;
  newReputation: BigNumber;
}
export type RequiredReputationUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber],
  RequiredReputationUpdatedEventObject
>;

export type RequiredReputationUpdatedEventFilter =
  TypedEventFilter<RequiredReputationUpdatedEvent>;

export interface VerificationAppliedEventObject {
  charityId: BigNumber;
  applicant: string;
  applicationId: BigNumber;
}
export type VerificationAppliedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  VerificationAppliedEventObject
>;

export type VerificationAppliedEventFilter =
  TypedEventFilter<VerificationAppliedEvent>;

export interface VerificationFeeUpdatedEventObject {
  oldFee: BigNumber;
  newFee: BigNumber;
}
export type VerificationFeeUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber],
  VerificationFeeUpdatedEventObject
>;

export type VerificationFeeUpdatedEventFilter =
  TypedEventFilter<VerificationFeeUpdatedEvent>;

export interface VerificationStatusUpdatedEventObject {
  charityId: BigNumber;
  oldStatus: number;
  newStatus: number;
  verifier: string;
  details: string;
}
export type VerificationStatusUpdatedEvent = TypedEvent<
  [BigNumber, number, number, string, string],
  VerificationStatusUpdatedEventObject
>;

export type VerificationStatusUpdatedEventFilter =
  TypedEventFilter<VerificationStatusUpdatedEvent>;

export interface CharityVerificationSystem extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CharityVerificationSystemInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    applicationCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    applyForVerification(
      charityId: PromiseOrValue<BigNumberish>,
      applicationDetails: PromiseOrValue<string>,
      supportingDocuments: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    charities(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        number,
        BigNumber,
        BigNumber,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean
      ] & {
        id: BigNumber;
        walletAddress: string;
        name: string;
        description: string;
        website: string;
        registrationNumber: string;
        country: string;
        category: string;
        status: number;
        verificationDate: BigNumber;
        lastUpdated: BigNumber;
        verifier: string;
        verificationDetails: string;
        rejectionReason: string;
        totalDonationsReceived: BigNumber;
        totalCampaigns: BigNumber;
        reputationScore: BigNumber;
        isFeatured: boolean;
      }
    >;

    charityCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    charityIdByAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    externalVerificationSources(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    feeRecipient(overrides?: CallOverrides): Promise<[string]>;

    getCharitiesByCategory(
      category: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getCharityInfo(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[CharityVerificationSystem.CharityInfoStructOutput]>;

    getCharityInfoByAddress(
      walletAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[CharityVerificationSystem.CharityInfoStructOutput]>;

    getFeaturedCharities(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    getTotalApplications(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTotalCharities(overrides?: CallOverrides): Promise<[BigNumber]>;

    getVerificationApplication(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[CharityVerificationSystem.VerificationApplicationStructOutput]>;

    getVerifiedCharities(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    governanceToken(overrides?: CallOverrides): Promise<[string]>;

    isCharityVerified(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isCharityVerifiedByAddress(
      walletAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    reactivateCharity(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerCharity(
      walletAddress: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      website: PromiseOrValue<string>,
      registrationNumber: PromiseOrValue<string>,
      country: PromiseOrValue<string>,
      category: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rejectVerification(
      charityId: PromiseOrValue<BigNumberish>,
      rejectionReason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requiredReputationForVerification(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    revokeVerification(
      charityId: PromiseOrValue<BigNumberish>,
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFeaturedStatus(
      charityId: PromiseOrValue<BigNumberish>,
      featured: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    suspendCharity(
      charityId: PromiseOrValue<BigNumberish>,
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    treasury(overrides?: CallOverrides): Promise<[string]>;

    updateExternalVerificationSource(
      source: PromiseOrValue<string>,
      allowed: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateFeeRecipient(
      newRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateReputationScore(
      charityId: PromiseOrValue<BigNumberish>,
      newScore: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateRequiredReputation(
      newReputation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateVerificationFee(
      newFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verificationApplications(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        BigNumber,
        number,
        string,
        string,
        BigNumber
      ] & {
        charityId: BigNumber;
        applicant: string;
        applicationDetails: string;
        supportingDocuments: string;
        applicationDate: BigNumber;
        status: number;
        reviewer: string;
        reviewNotes: string;
        reviewDate: BigNumber;
      }
    >;

    verificationDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    verificationFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    verifyCharity(
      charityId: PromiseOrValue<BigNumberish>,
      verificationDetails: PromiseOrValue<string>,
      verificationSource: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  applicationCount(overrides?: CallOverrides): Promise<BigNumber>;

  applyForVerification(
    charityId: PromiseOrValue<BigNumberish>,
    applicationDetails: PromiseOrValue<string>,
    supportingDocuments: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  charities(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      number,
      BigNumber,
      BigNumber,
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean
    ] & {
      id: BigNumber;
      walletAddress: string;
      name: string;
      description: string;
      website: string;
      registrationNumber: string;
      country: string;
      category: string;
      status: number;
      verificationDate: BigNumber;
      lastUpdated: BigNumber;
      verifier: string;
      verificationDetails: string;
      rejectionReason: string;
      totalDonationsReceived: BigNumber;
      totalCampaigns: BigNumber;
      reputationScore: BigNumber;
      isFeatured: boolean;
    }
  >;

  charityCount(overrides?: CallOverrides): Promise<BigNumber>;

  charityIdByAddress(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  externalVerificationSources(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  feeRecipient(overrides?: CallOverrides): Promise<string>;

  getCharitiesByCategory(
    category: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getCharityInfo(
    charityId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<CharityVerificationSystem.CharityInfoStructOutput>;

  getCharityInfoByAddress(
    walletAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<CharityVerificationSystem.CharityInfoStructOutput>;

  getFeaturedCharities(overrides?: CallOverrides): Promise<BigNumber[]>;

  getTotalApplications(overrides?: CallOverrides): Promise<BigNumber>;

  getTotalCharities(overrides?: CallOverrides): Promise<BigNumber>;

  getVerificationApplication(
    charityId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<CharityVerificationSystem.VerificationApplicationStructOutput>;

  getVerifiedCharities(overrides?: CallOverrides): Promise<BigNumber[]>;

  governanceToken(overrides?: CallOverrides): Promise<string>;

  isCharityVerified(
    charityId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isCharityVerifiedByAddress(
    walletAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  reactivateCharity(
    charityId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerCharity(
    walletAddress: PromiseOrValue<string>,
    name: PromiseOrValue<string>,
    description: PromiseOrValue<string>,
    website: PromiseOrValue<string>,
    registrationNumber: PromiseOrValue<string>,
    country: PromiseOrValue<string>,
    category: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rejectVerification(
    charityId: PromiseOrValue<BigNumberish>,
    rejectionReason: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requiredReputationForVerification(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  revokeVerification(
    charityId: PromiseOrValue<BigNumberish>,
    reason: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFeaturedStatus(
    charityId: PromiseOrValue<BigNumberish>,
    featured: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  suspendCharity(
    charityId: PromiseOrValue<BigNumberish>,
    reason: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  treasury(overrides?: CallOverrides): Promise<string>;

  updateExternalVerificationSource(
    source: PromiseOrValue<string>,
    allowed: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateFeeRecipient(
    newRecipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateReputationScore(
    charityId: PromiseOrValue<BigNumberish>,
    newScore: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateRequiredReputation(
    newReputation: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateVerificationFee(
    newFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verificationApplications(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      string,
      string,
      BigNumber,
      number,
      string,
      string,
      BigNumber
    ] & {
      charityId: BigNumber;
      applicant: string;
      applicationDetails: string;
      supportingDocuments: string;
      applicationDate: BigNumber;
      status: number;
      reviewer: string;
      reviewNotes: string;
      reviewDate: BigNumber;
    }
  >;

  verificationDuration(overrides?: CallOverrides): Promise<BigNumber>;

  verificationFee(overrides?: CallOverrides): Promise<BigNumber>;

  verifyCharity(
    charityId: PromiseOrValue<BigNumberish>,
    verificationDetails: PromiseOrValue<string>,
    verificationSource: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    applicationCount(overrides?: CallOverrides): Promise<BigNumber>;

    applyForVerification(
      charityId: PromiseOrValue<BigNumberish>,
      applicationDetails: PromiseOrValue<string>,
      supportingDocuments: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    charities(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        number,
        BigNumber,
        BigNumber,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean
      ] & {
        id: BigNumber;
        walletAddress: string;
        name: string;
        description: string;
        website: string;
        registrationNumber: string;
        country: string;
        category: string;
        status: number;
        verificationDate: BigNumber;
        lastUpdated: BigNumber;
        verifier: string;
        verificationDetails: string;
        rejectionReason: string;
        totalDonationsReceived: BigNumber;
        totalCampaigns: BigNumber;
        reputationScore: BigNumber;
        isFeatured: boolean;
      }
    >;

    charityCount(overrides?: CallOverrides): Promise<BigNumber>;

    charityIdByAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    externalVerificationSources(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    feeRecipient(overrides?: CallOverrides): Promise<string>;

    getCharitiesByCategory(
      category: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getCharityInfo(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<CharityVerificationSystem.CharityInfoStructOutput>;

    getCharityInfoByAddress(
      walletAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<CharityVerificationSystem.CharityInfoStructOutput>;

    getFeaturedCharities(overrides?: CallOverrides): Promise<BigNumber[]>;

    getTotalApplications(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalCharities(overrides?: CallOverrides): Promise<BigNumber>;

    getVerificationApplication(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<CharityVerificationSystem.VerificationApplicationStructOutput>;

    getVerifiedCharities(overrides?: CallOverrides): Promise<BigNumber[]>;

    governanceToken(overrides?: CallOverrides): Promise<string>;

    isCharityVerified(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isCharityVerifiedByAddress(
      walletAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    reactivateCharity(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerCharity(
      walletAddress: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      website: PromiseOrValue<string>,
      registrationNumber: PromiseOrValue<string>,
      country: PromiseOrValue<string>,
      category: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rejectVerification(
      charityId: PromiseOrValue<BigNumberish>,
      rejectionReason: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    requiredReputationForVerification(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revokeVerification(
      charityId: PromiseOrValue<BigNumberish>,
      reason: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeaturedStatus(
      charityId: PromiseOrValue<BigNumberish>,
      featured: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    suspendCharity(
      charityId: PromiseOrValue<BigNumberish>,
      reason: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    treasury(overrides?: CallOverrides): Promise<string>;

    updateExternalVerificationSource(
      source: PromiseOrValue<string>,
      allowed: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateFeeRecipient(
      newRecipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateReputationScore(
      charityId: PromiseOrValue<BigNumberish>,
      newScore: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRequiredReputation(
      newReputation: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateVerificationFee(
      newFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    verificationApplications(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        BigNumber,
        number,
        string,
        string,
        BigNumber
      ] & {
        charityId: BigNumber;
        applicant: string;
        applicationDetails: string;
        supportingDocuments: string;
        applicationDate: BigNumber;
        status: number;
        reviewer: string;
        reviewNotes: string;
        reviewDate: BigNumber;
      }
    >;

    verificationDuration(overrides?: CallOverrides): Promise<BigNumber>;

    verificationFee(overrides?: CallOverrides): Promise<BigNumber>;

    verifyCharity(
      charityId: PromiseOrValue<BigNumberish>,
      verificationDetails: PromiseOrValue<string>,
      verificationSource: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CharityFeatured(uint256,bool)"(
      charityId?: PromiseOrValue<BigNumberish> | null,
      featured?: null
    ): CharityFeaturedEventFilter;
    CharityFeatured(
      charityId?: PromiseOrValue<BigNumberish> | null,
      featured?: null
    ): CharityFeaturedEventFilter;

    "CharityRegistered(uint256,address,string,address)"(
      charityId?: PromiseOrValue<BigNumberish> | null,
      walletAddress?: PromiseOrValue<string> | null,
      name?: null,
      registrar?: PromiseOrValue<string> | null
    ): CharityRegisteredEventFilter;
    CharityRegistered(
      charityId?: PromiseOrValue<BigNumberish> | null,
      walletAddress?: PromiseOrValue<string> | null,
      name?: null,
      registrar?: PromiseOrValue<string> | null
    ): CharityRegisteredEventFilter;

    "ExternalVerificationSourceUpdated(string,bool)"(
      source?: null,
      allowed?: null
    ): ExternalVerificationSourceUpdatedEventFilter;
    ExternalVerificationSourceUpdated(
      source?: null,
      allowed?: null
    ): ExternalVerificationSourceUpdatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "RequiredReputationUpdated(uint256,uint256)"(
      oldReputation?: null,
      newReputation?: null
    ): RequiredReputationUpdatedEventFilter;
    RequiredReputationUpdated(
      oldReputation?: null,
      newReputation?: null
    ): RequiredReputationUpdatedEventFilter;

    "VerificationApplied(uint256,address,uint256)"(
      charityId?: PromiseOrValue<BigNumberish> | null,
      applicant?: PromiseOrValue<string> | null,
      applicationId?: null
    ): VerificationAppliedEventFilter;
    VerificationApplied(
      charityId?: PromiseOrValue<BigNumberish> | null,
      applicant?: PromiseOrValue<string> | null,
      applicationId?: null
    ): VerificationAppliedEventFilter;

    "VerificationFeeUpdated(uint256,uint256)"(
      oldFee?: null,
      newFee?: null
    ): VerificationFeeUpdatedEventFilter;
    VerificationFeeUpdated(
      oldFee?: null,
      newFee?: null
    ): VerificationFeeUpdatedEventFilter;

    "VerificationStatusUpdated(uint256,uint8,uint8,address,string)"(
      charityId?: PromiseOrValue<BigNumberish> | null,
      oldStatus?: null,
      newStatus?: null,
      verifier?: PromiseOrValue<string> | null,
      details?: null
    ): VerificationStatusUpdatedEventFilter;
    VerificationStatusUpdated(
      charityId?: PromiseOrValue<BigNumberish> | null,
      oldStatus?: null,
      newStatus?: null,
      verifier?: PromiseOrValue<string> | null,
      details?: null
    ): VerificationStatusUpdatedEventFilter;
  };

  estimateGas: {
    applicationCount(overrides?: CallOverrides): Promise<BigNumber>;

    applyForVerification(
      charityId: PromiseOrValue<BigNumberish>,
      applicationDetails: PromiseOrValue<string>,
      supportingDocuments: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    charities(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    charityCount(overrides?: CallOverrides): Promise<BigNumber>;

    charityIdByAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    externalVerificationSources(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    feeRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    getCharitiesByCategory(
      category: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCharityInfo(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCharityInfoByAddress(
      walletAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeaturedCharities(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalApplications(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalCharities(overrides?: CallOverrides): Promise<BigNumber>;

    getVerificationApplication(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVerifiedCharities(overrides?: CallOverrides): Promise<BigNumber>;

    governanceToken(overrides?: CallOverrides): Promise<BigNumber>;

    isCharityVerified(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isCharityVerifiedByAddress(
      walletAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    reactivateCharity(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerCharity(
      walletAddress: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      website: PromiseOrValue<string>,
      registrationNumber: PromiseOrValue<string>,
      country: PromiseOrValue<string>,
      category: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rejectVerification(
      charityId: PromiseOrValue<BigNumberish>,
      rejectionReason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requiredReputationForVerification(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revokeVerification(
      charityId: PromiseOrValue<BigNumberish>,
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFeaturedStatus(
      charityId: PromiseOrValue<BigNumberish>,
      featured: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    suspendCharity(
      charityId: PromiseOrValue<BigNumberish>,
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<BigNumber>;

    updateExternalVerificationSource(
      source: PromiseOrValue<string>,
      allowed: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateFeeRecipient(
      newRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateReputationScore(
      charityId: PromiseOrValue<BigNumberish>,
      newScore: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateRequiredReputation(
      newReputation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateVerificationFee(
      newFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verificationApplications(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verificationDuration(overrides?: CallOverrides): Promise<BigNumber>;

    verificationFee(overrides?: CallOverrides): Promise<BigNumber>;

    verifyCharity(
      charityId: PromiseOrValue<BigNumberish>,
      verificationDetails: PromiseOrValue<string>,
      verificationSource: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    applicationCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    applyForVerification(
      charityId: PromiseOrValue<BigNumberish>,
      applicationDetails: PromiseOrValue<string>,
      supportingDocuments: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    charities(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    charityCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    charityIdByAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    externalVerificationSources(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    feeRecipient(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCharitiesByCategory(
      category: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCharityInfo(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCharityInfoByAddress(
      walletAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeaturedCharities(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalApplications(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalCharities(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVerificationApplication(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVerifiedCharities(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    governanceToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isCharityVerified(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isCharityVerifiedByAddress(
      walletAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reactivateCharity(
      charityId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerCharity(
      walletAddress: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      website: PromiseOrValue<string>,
      registrationNumber: PromiseOrValue<string>,
      country: PromiseOrValue<string>,
      category: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rejectVerification(
      charityId: PromiseOrValue<BigNumberish>,
      rejectionReason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requiredReputationForVerification(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    revokeVerification(
      charityId: PromiseOrValue<BigNumberish>,
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFeaturedStatus(
      charityId: PromiseOrValue<BigNumberish>,
      featured: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    suspendCharity(
      charityId: PromiseOrValue<BigNumberish>,
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    treasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateExternalVerificationSource(
      source: PromiseOrValue<string>,
      allowed: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateFeeRecipient(
      newRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateReputationScore(
      charityId: PromiseOrValue<BigNumberish>,
      newScore: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateRequiredReputation(
      newReputation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateVerificationFee(
      newFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verificationApplications(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verificationDuration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verificationFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    verifyCharity(
      charityId: PromiseOrValue<BigNumberish>,
      verificationDetails: PromiseOrValue<string>,
      verificationSource: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
