/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace EnhancedEscrow {
  export type DetailedReputationScoreStruct = {
    totalPoints: BigNumberish;
    reviewCount: BigNumberish;
    averageRating: BigNumberish;
    successfulTransactions: BigNumberish;
    disputesWon: BigNumberish;
    disputesLost: BigNumberish;
    tier: BigNumberish;
    lastActivityTimestamp: BigNumberish;
    isSuspended: boolean;
    suspensionEndTime: BigNumberish;
  };

  export type DetailedReputationScoreStructOutput = [
    totalPoints: bigint,
    reviewCount: bigint,
    averageRating: bigint,
    successfulTransactions: bigint,
    disputesWon: bigint,
    disputesLost: bigint,
    tier: bigint,
    lastActivityTimestamp: bigint,
    isSuspended: boolean,
    suspensionEndTime: bigint
  ] & {
    totalPoints: bigint;
    reviewCount: bigint;
    averageRating: bigint;
    successfulTransactions: bigint;
    disputesWon: bigint;
    disputesLost: bigint;
    tier: bigint;
    lastActivityTimestamp: bigint;
    isSuspended: boolean;
    suspensionEndTime: bigint;
  };
}

export interface EnhancedEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_PLATFORM_FEE"
      | "MIN_VOTING_POWER"
      | "REPUTATION_DECAY_PERIOD"
      | "VOTING_PERIOD"
      | "addSignature"
      | "arbitratorFees"
      | "authorizeArbitrator"
      | "authorizedArbitrators"
      | "autoResolveDispute"
      | "calculateWeightedScore"
      | "castHelpfulVote"
      | "castVote"
      | "chainId"
      | "confirmDelivery"
      | "createEscrow"
      | "createEscrowWithSecurity"
      | "detailedReputationScores"
      | "escrowChainId"
      | "escrows"
      | "executeEmergencyRefund"
      | "getDetailedReputation"
      | "getEscrowChainId"
      | "getReputationTier"
      | "getTopSellers"
      | "getUserReviews"
      | "governance"
      | "ldaoToken"
      | "lockFunds"
      | "nextEscrowId"
      | "nextReviewId"
      | "openDispute"
      | "owner"
      | "platformFeePercentage"
      | "renounceOwnership"
      | "resolveDisputeByArbitrator"
      | "reviews"
      | "setArbitratorFee"
      | "setGovernance"
      | "setLDAOToken"
      | "setPlatformFee"
      | "submitMarketplaceReview"
      | "suspendUser"
      | "transferOwnership"
      | "userEscrows"
      | "userReviews"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArbitratorAppointed"
      | "DeliveryConfirmed"
      | "DisputeOpened"
      | "EmergencyRefund"
      | "EscrowCreated"
      | "EscrowResolved"
      | "FundsLocked"
      | "OwnershipTransferred"
      | "ReputationUpdated"
      | "ReviewSubmitted"
      | "UserSuspended"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_PLATFORM_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_VOTING_POWER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REPUTATION_DECAY_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addSignature",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "arbitratorFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeArbitrator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedArbitrators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "autoResolveDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateWeightedScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "castHelpfulVote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castVote",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "chainId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "confirmDelivery",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrowWithSecurity",
    values: [
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "detailedReputationScores",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowChainId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeEmergencyRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDetailedReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowChainId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationTier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopSellers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserReviews",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ldaoToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lockFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextEscrowId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextReviewId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDisputeByArbitrator",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "reviews",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setArbitratorFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLDAOToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitMarketplaceReview",
    values: [BigNumberish, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "suspendUser",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userEscrows",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userReviews",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_PLATFORM_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_VOTING_POWER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REPUTATION_DECAY_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "arbitratorFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeArbitrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedArbitrators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoResolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateWeightedScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castHelpfulVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "chainId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrowWithSecurity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "detailedReputationScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeEmergencyRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDetailedReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTopSellers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserReviews",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ldaoToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockFunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextEscrowId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextReviewId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDisputeByArbitrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reviews", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setArbitratorFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLDAOToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitMarketplaceReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suspendUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userReviews",
    data: BytesLike
  ): Result;
}

export namespace ArbitratorAppointedEvent {
  export type InputTuple = [escrowId: BigNumberish, arbitrator: AddressLike];
  export type OutputTuple = [escrowId: bigint, arbitrator: string];
  export interface OutputObject {
    escrowId: bigint;
    arbitrator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliveryConfirmedEvent {
  export type InputTuple = [escrowId: BigNumberish, deliveryInfo: string];
  export type OutputTuple = [escrowId: bigint, deliveryInfo: string];
  export interface OutputObject {
    escrowId: bigint;
    deliveryInfo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeOpenedEvent {
  export type InputTuple = [escrowId: BigNumberish, method: BigNumberish];
  export type OutputTuple = [escrowId: bigint, method: bigint];
  export interface OutputObject {
    escrowId: bigint;
    method: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyRefundEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [escrowId: bigint, buyer: string, amount: bigint];
  export interface OutputObject {
    escrowId: bigint;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    buyer: string,
    seller: string,
    amount: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    buyer: string;
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowResolvedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    resolution: BigNumberish,
    winner: AddressLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    resolution: bigint,
    winner: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    resolution: bigint;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsLockedEvent {
  export type InputTuple = [escrowId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [escrowId: bigint, amount: bigint];
  export interface OutputObject {
    escrowId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    newScore: BigNumberish,
    newTier: BigNumberish
  ];
  export type OutputTuple = [user: string, newScore: bigint, newTier: bigint];
  export interface OutputObject {
    user: string;
    newScore: bigint;
    newTier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewSubmittedEvent {
  export type InputTuple = [
    reviewId: BigNumberish,
    reviewer: AddressLike,
    reviewee: AddressLike,
    rating: BigNumberish
  ];
  export type OutputTuple = [
    reviewId: bigint,
    reviewer: string,
    reviewee: string,
    rating: bigint
  ];
  export interface OutputObject {
    reviewId: bigint;
    reviewer: string;
    reviewee: string;
    rating: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserSuspendedEvent {
  export type InputTuple = [
    user: AddressLike,
    duration: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [user: string, duration: bigint, reason: string];
  export interface OutputObject {
    user: string;
    duration: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    voter: AddressLike,
    forBuyer: boolean,
    votingPower: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    voter: string,
    forBuyer: boolean,
    votingPower: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    voter: string;
    forBuyer: boolean;
    votingPower: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EnhancedEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): EnhancedEscrow;
  waitForDeployment(): Promise<this>;

  interface: EnhancedEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_PLATFORM_FEE: TypedContractMethod<[], [bigint], "view">;

  MIN_VOTING_POWER: TypedContractMethod<[], [bigint], "view">;

  REPUTATION_DECAY_PERIOD: TypedContractMethod<[], [bigint], "view">;

  VOTING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  addSignature: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  arbitratorFees: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  authorizeArbitrator: TypedContractMethod<
    [arbitrator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  authorizedArbitrators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  autoResolveDispute: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  calculateWeightedScore: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  castHelpfulVote: TypedContractMethod<
    [reviewId: BigNumberish],
    [void],
    "nonpayable"
  >;

  castVote: TypedContractMethod<
    [escrowId: BigNumberish, forBuyer: boolean],
    [void],
    "nonpayable"
  >;

  chainId: TypedContractMethod<[], [bigint], "view">;

  confirmDelivery: TypedContractMethod<
    [escrowId: BigNumberish, deliveryInfo: string],
    [void],
    "nonpayable"
  >;

  createEscrow: TypedContractMethod<
    [
      listingId: BigNumberish,
      seller: AddressLike,
      tokenAddress: AddressLike,
      amount: BigNumberish,
      deliveryDeadline: BigNumberish,
      resolutionMethod: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  createEscrowWithSecurity: TypedContractMethod<
    [
      listingId: BigNumberish,
      seller: AddressLike,
      tokenAddress: AddressLike,
      amount: BigNumberish,
      deliveryDeadline: BigNumberish,
      resolutionMethod: BigNumberish,
      requiresMultiSig: boolean,
      multiSigThreshold: BigNumberish,
      timeLockDuration: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  detailedReputationScores: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        totalPoints: bigint;
        reviewCount: bigint;
        averageRating: bigint;
        successfulTransactions: bigint;
        disputesWon: bigint;
        disputesLost: bigint;
        tier: bigint;
        lastActivityTimestamp: bigint;
        isSuspended: boolean;
        suspensionEndTime: bigint;
      }
    ],
    "view"
  >;

  escrowChainId: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  escrows: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        listingId: bigint;
        buyer: string;
        seller: string;
        tokenAddress: string;
        amount: bigint;
        feeAmount: bigint;
        deliveryInfo: string;
        deliveryDeadline: bigint;
        createdAt: bigint;
        resolvedAt: bigint;
        status: bigint;
        resolutionMethod: bigint;
        votesForBuyer: bigint;
        votesForSeller: bigint;
        totalVotingPower: bigint;
        appointedArbitrator: string;
        evidenceSubmitted: string;
        requiresMultiSig: boolean;
        multiSigThreshold: bigint;
        signatureCount: bigint;
        timeLockExpiry: bigint;
        emergencyRefundEnabled: boolean;
      }
    ],
    "view"
  >;

  executeEmergencyRefund: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDetailedReputation: TypedContractMethod<
    [user: AddressLike],
    [EnhancedEscrow.DetailedReputationScoreStructOutput],
    "view"
  >;

  getEscrowChainId: TypedContractMethod<
    [escrowId: BigNumberish],
    [bigint],
    "view"
  >;

  getReputationTier: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getTopSellers: TypedContractMethod<
    [limit: BigNumberish],
    [[string[], bigint[]] & { sellers: string[]; scores: bigint[] }],
    "view"
  >;

  getUserReviews: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  governance: TypedContractMethod<[], [string], "view">;

  ldaoToken: TypedContractMethod<[], [string], "view">;

  lockFunds: TypedContractMethod<[escrowId: BigNumberish], [void], "payable">;

  nextEscrowId: TypedContractMethod<[], [bigint], "view">;

  nextReviewId: TypedContractMethod<[], [bigint], "view">;

  openDispute: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeePercentage: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDisputeByArbitrator: TypedContractMethod<
    [escrowId: BigNumberish, buyerWins: boolean],
    [void],
    "nonpayable"
  >;

  reviews: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        reviewer: string;
        reviewee: string;
        escrowId: bigint;
        rating: bigint;
        reviewText: string;
        timestamp: bigint;
        isVerified: boolean;
        helpfulVotes: bigint;
      }
    ],
    "view"
  >;

  setArbitratorFee: TypedContractMethod<
    [arbitrator: AddressLike, fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGovernance: TypedContractMethod<
    [newGovernance: AddressLike],
    [void],
    "nonpayable"
  >;

  setLDAOToken: TypedContractMethod<
    [newToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitMarketplaceReview: TypedContractMethod<
    [
      escrowId: BigNumberish,
      reviewee: AddressLike,
      rating: BigNumberish,
      reviewText: string
    ],
    [bigint],
    "nonpayable"
  >;

  suspendUser: TypedContractMethod<
    [user: AddressLike, duration: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userEscrows: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userReviews: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_PLATFORM_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_VOTING_POWER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REPUTATION_DECAY_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOTING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addSignature"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "arbitratorFees"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizeArbitrator"
  ): TypedContractMethod<
    [arbitrator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedArbitrators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "autoResolveDispute"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateWeightedScore"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "castHelpfulVote"
  ): TypedContractMethod<[reviewId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [escrowId: BigNumberish, forBuyer: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "chainId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "confirmDelivery"
  ): TypedContractMethod<
    [escrowId: BigNumberish, deliveryInfo: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      listingId: BigNumberish,
      seller: AddressLike,
      tokenAddress: AddressLike,
      amount: BigNumberish,
      deliveryDeadline: BigNumberish,
      resolutionMethod: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createEscrowWithSecurity"
  ): TypedContractMethod<
    [
      listingId: BigNumberish,
      seller: AddressLike,
      tokenAddress: AddressLike,
      amount: BigNumberish,
      deliveryDeadline: BigNumberish,
      resolutionMethod: BigNumberish,
      requiresMultiSig: boolean,
      multiSigThreshold: BigNumberish,
      timeLockDuration: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "detailedReputationScores"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        totalPoints: bigint;
        reviewCount: bigint;
        averageRating: bigint;
        successfulTransactions: bigint;
        disputesWon: bigint;
        disputesLost: bigint;
        tier: bigint;
        lastActivityTimestamp: bigint;
        isSuspended: boolean;
        suspensionEndTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "escrowChainId"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        listingId: bigint;
        buyer: string;
        seller: string;
        tokenAddress: string;
        amount: bigint;
        feeAmount: bigint;
        deliveryInfo: string;
        deliveryDeadline: bigint;
        createdAt: bigint;
        resolvedAt: bigint;
        status: bigint;
        resolutionMethod: bigint;
        votesForBuyer: bigint;
        votesForSeller: bigint;
        totalVotingPower: bigint;
        appointedArbitrator: string;
        evidenceSubmitted: string;
        requiresMultiSig: boolean;
        multiSigThreshold: bigint;
        signatureCount: bigint;
        timeLockExpiry: bigint;
        emergencyRefundEnabled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeEmergencyRefund"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDetailedReputation"
  ): TypedContractMethod<
    [user: AddressLike],
    [EnhancedEscrow.DetailedReputationScoreStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrowChainId"
  ): TypedContractMethod<[escrowId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReputationTier"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTopSellers"
  ): TypedContractMethod<
    [limit: BigNumberish],
    [[string[], bigint[]] & { sellers: string[]; scores: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserReviews"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "governance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ldaoToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lockFunds"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "nextEscrowId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextReviewId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDisputeByArbitrator"
  ): TypedContractMethod<
    [escrowId: BigNumberish, buyerWins: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reviews"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        reviewer: string;
        reviewee: string;
        escrowId: bigint;
        rating: bigint;
        reviewText: string;
        timestamp: bigint;
        isVerified: boolean;
        helpfulVotes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setArbitratorFee"
  ): TypedContractMethod<
    [arbitrator: AddressLike, fee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGovernance"
  ): TypedContractMethod<[newGovernance: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLDAOToken"
  ): TypedContractMethod<[newToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitMarketplaceReview"
  ): TypedContractMethod<
    [
      escrowId: BigNumberish,
      reviewee: AddressLike,
      rating: BigNumberish,
      reviewText: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "suspendUser"
  ): TypedContractMethod<
    [user: AddressLike, duration: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userEscrows"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userReviews"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "ArbitratorAppointed"
  ): TypedContractEvent<
    ArbitratorAppointedEvent.InputTuple,
    ArbitratorAppointedEvent.OutputTuple,
    ArbitratorAppointedEvent.OutputObject
  >;
  getEvent(
    key: "DeliveryConfirmed"
  ): TypedContractEvent<
    DeliveryConfirmedEvent.InputTuple,
    DeliveryConfirmedEvent.OutputTuple,
    DeliveryConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeOpened"
  ): TypedContractEvent<
    DisputeOpenedEvent.InputTuple,
    DisputeOpenedEvent.OutputTuple,
    DisputeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyRefund"
  ): TypedContractEvent<
    EmergencyRefundEvent.InputTuple,
    EmergencyRefundEvent.OutputTuple,
    EmergencyRefundEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowResolved"
  ): TypedContractEvent<
    EscrowResolvedEvent.InputTuple,
    EscrowResolvedEvent.OutputTuple,
    EscrowResolvedEvent.OutputObject
  >;
  getEvent(
    key: "FundsLocked"
  ): TypedContractEvent<
    FundsLockedEvent.InputTuple,
    FundsLockedEvent.OutputTuple,
    FundsLockedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewSubmitted"
  ): TypedContractEvent<
    ReviewSubmittedEvent.InputTuple,
    ReviewSubmittedEvent.OutputTuple,
    ReviewSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "UserSuspended"
  ): TypedContractEvent<
    UserSuspendedEvent.InputTuple,
    UserSuspendedEvent.OutputTuple,
    UserSuspendedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "ArbitratorAppointed(uint256,address)": TypedContractEvent<
      ArbitratorAppointedEvent.InputTuple,
      ArbitratorAppointedEvent.OutputTuple,
      ArbitratorAppointedEvent.OutputObject
    >;
    ArbitratorAppointed: TypedContractEvent<
      ArbitratorAppointedEvent.InputTuple,
      ArbitratorAppointedEvent.OutputTuple,
      ArbitratorAppointedEvent.OutputObject
    >;

    "DeliveryConfirmed(uint256,string)": TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;
    DeliveryConfirmed: TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;

    "DisputeOpened(uint256,uint8)": TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;
    DisputeOpened: TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;

    "EmergencyRefund(uint256,address,uint256)": TypedContractEvent<
      EmergencyRefundEvent.InputTuple,
      EmergencyRefundEvent.OutputTuple,
      EmergencyRefundEvent.OutputObject
    >;
    EmergencyRefund: TypedContractEvent<
      EmergencyRefundEvent.InputTuple,
      EmergencyRefundEvent.OutputTuple,
      EmergencyRefundEvent.OutputObject
    >;

    "EscrowCreated(uint256,address,address,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowResolved(uint256,uint8,address)": TypedContractEvent<
      EscrowResolvedEvent.InputTuple,
      EscrowResolvedEvent.OutputTuple,
      EscrowResolvedEvent.OutputObject
    >;
    EscrowResolved: TypedContractEvent<
      EscrowResolvedEvent.InputTuple,
      EscrowResolvedEvent.OutputTuple,
      EscrowResolvedEvent.OutputObject
    >;

    "FundsLocked(uint256,uint256)": TypedContractEvent<
      FundsLockedEvent.InputTuple,
      FundsLockedEvent.OutputTuple,
      FundsLockedEvent.OutputObject
    >;
    FundsLocked: TypedContractEvent<
      FundsLockedEvent.InputTuple,
      FundsLockedEvent.OutputTuple,
      FundsLockedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256,uint8)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "ReviewSubmitted(uint256,address,address,uint8)": TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;
    ReviewSubmitted: TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;

    "UserSuspended(address,uint256,string)": TypedContractEvent<
      UserSuspendedEvent.InputTuple,
      UserSuspendedEvent.OutputTuple,
      UserSuspendedEvent.OutputObject
    >;
    UserSuspended: TypedContractEvent<
      UserSuspendedEvent.InputTuple,
      UserSuspendedEvent.OutputTuple,
      UserSuspendedEvent.OutputObject
    >;

    "VoteCast(uint256,address,bool,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
