/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ISubDAOInterface extends utils.Interface {
  functions: {
    "getCreator()": FunctionFragment;
    "getDescription()": FunctionFragment;
    "getName()": FunctionFragment;
    "getRegion()": FunctionFragment;
    "initialize(string,string,string,address,address[])": FunctionFragment;
    "isActive()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getCreator"
      | "getDescription"
      | "getName"
      | "getRegion"
      | "initialize"
      | "isActive"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCreator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDescription",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getName", values?: undefined): string;
  encodeFunctionData(functionFragment: "getRegion", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "isActive", values?: undefined): string;

  decodeFunctionResult(functionFragment: "getCreator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRegion", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;

  events: {};
}

export interface ISubDAO extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISubDAOInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getCreator(overrides?: CallOverrides): Promise<[string]>;

    getDescription(overrides?: CallOverrides): Promise<[string]>;

    getName(overrides?: CallOverrides): Promise<[string]>;

    getRegion(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      name: PromiseOrValue<string>,
      region: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      creator: PromiseOrValue<string>,
      initialMembers: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isActive(overrides?: CallOverrides): Promise<[boolean]>;
  };

  getCreator(overrides?: CallOverrides): Promise<string>;

  getDescription(overrides?: CallOverrides): Promise<string>;

  getName(overrides?: CallOverrides): Promise<string>;

  getRegion(overrides?: CallOverrides): Promise<string>;

  initialize(
    name: PromiseOrValue<string>,
    region: PromiseOrValue<string>,
    description: PromiseOrValue<string>,
    creator: PromiseOrValue<string>,
    initialMembers: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isActive(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    getCreator(overrides?: CallOverrides): Promise<string>;

    getDescription(overrides?: CallOverrides): Promise<string>;

    getName(overrides?: CallOverrides): Promise<string>;

    getRegion(overrides?: CallOverrides): Promise<string>;

    initialize(
      name: PromiseOrValue<string>,
      region: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      creator: PromiseOrValue<string>,
      initialMembers: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    isActive(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getCreator(overrides?: CallOverrides): Promise<BigNumber>;

    getDescription(overrides?: CallOverrides): Promise<BigNumber>;

    getName(overrides?: CallOverrides): Promise<BigNumber>;

    getRegion(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      name: PromiseOrValue<string>,
      region: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      creator: PromiseOrValue<string>,
      initialMembers: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isActive(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getCreator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDescription(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRegion(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      name: PromiseOrValue<string>,
      region: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      creator: PromiseOrValue<string>,
      initialMembers: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isActive(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
