/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FollowModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptFollowRequest"
      | "addToFollowList"
      | "follow"
      | "followLists"
      | "followRequests"
      | "followTiers"
      | "followerCount"
      | "followingCount"
      | "follows"
      | "getFollowList"
      | "getUserLists"
      | "hasFollowRequest"
      | "isFollowing"
      | "isMuted"
      | "muteUser"
      | "muted"
      | "owner"
      | "profileRegistry"
      | "rejectFollowRequest"
      | "removeFromFollowList"
      | "renounceOwnership"
      | "requestFollow"
      | "setFollowTier"
      | "setProfileRegistry"
      | "transferOwnership"
      | "unfollow"
      | "unmuteUser"
      | "userLists"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FollowRequestAccepted"
      | "FollowRequestRejected"
      | "FollowRequested"
      | "FollowTierSet"
      | "Followed"
      | "OwnershipTransferred"
      | "Unfollowed"
      | "UserMuted"
      | "UserUnmuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptFollowRequest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addToFollowList",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "follow", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "followLists",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "followRequests",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "followTiers",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "followerCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "followingCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "follows",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFollowList",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserLists",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasFollowRequest",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFollowing",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMuted",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "muteUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "muted",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "profileRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rejectFollowRequest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromFollowList",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestFollow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFollowTier",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProfileRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unfollow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unmuteUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userLists",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptFollowRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToFollowList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "follow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "followLists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "followRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "followTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "followerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "followingCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "follows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFollowList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserLists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasFollowRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFollowing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMuted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "muteUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "muted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "profileRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectFollowRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromFollowList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFollow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFollowTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProfileRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unfollow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unmuteUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userLists", data: BytesLike): Result;
}

export namespace FollowRequestAcceptedEvent {
  export type InputTuple = [follower: AddressLike, following: AddressLike];
  export type OutputTuple = [follower: string, following: string];
  export interface OutputObject {
    follower: string;
    following: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FollowRequestRejectedEvent {
  export type InputTuple = [follower: AddressLike, following: AddressLike];
  export type OutputTuple = [follower: string, following: string];
  export interface OutputObject {
    follower: string;
    following: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FollowRequestedEvent {
  export type InputTuple = [follower: AddressLike, following: AddressLike];
  export type OutputTuple = [follower: string, following: string];
  export interface OutputObject {
    follower: string;
    following: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FollowTierSetEvent {
  export type InputTuple = [
    follower: AddressLike,
    following: AddressLike,
    tier: BigNumberish
  ];
  export type OutputTuple = [follower: string, following: string, tier: bigint];
  export interface OutputObject {
    follower: string;
    following: string;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FollowedEvent {
  export type InputTuple = [follower: AddressLike, following: AddressLike];
  export type OutputTuple = [follower: string, following: string];
  export interface OutputObject {
    follower: string;
    following: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnfollowedEvent {
  export type InputTuple = [follower: AddressLike, following: AddressLike];
  export type OutputTuple = [follower: string, following: string];
  export interface OutputObject {
    follower: string;
    following: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserMutedEvent {
  export type InputTuple = [user: AddressLike, mutedUser: AddressLike];
  export type OutputTuple = [user: string, mutedUser: string];
  export interface OutputObject {
    user: string;
    mutedUser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserUnmutedEvent {
  export type InputTuple = [user: AddressLike, unmutedUser: AddressLike];
  export type OutputTuple = [user: string, unmutedUser: string];
  export interface OutputObject {
    user: string;
    unmutedUser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FollowModule extends BaseContract {
  connect(runner?: ContractRunner | null): FollowModule;
  waitForDeployment(): Promise<this>;

  interface: FollowModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptFollowRequest: TypedContractMethod<
    [follower: AddressLike],
    [void],
    "nonpayable"
  >;

  addToFollowList: TypedContractMethod<
    [listName: string, user: AddressLike],
    [void],
    "nonpayable"
  >;

  follow: TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  followLists: TypedContractMethod<
    [arg0: AddressLike, arg1: string, arg2: BigNumberish],
    [string],
    "view"
  >;

  followRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  followTiers: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  followerCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  followingCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  follows: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getFollowList: TypedContractMethod<[listName: string], [string[]], "view">;

  getUserLists: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  hasFollowRequest: TypedContractMethod<
    [follower: AddressLike, following: AddressLike],
    [boolean],
    "view"
  >;

  isFollowing: TypedContractMethod<
    [follower: AddressLike, following: AddressLike],
    [boolean],
    "view"
  >;

  isMuted: TypedContractMethod<
    [user: AddressLike, mutedUser: AddressLike],
    [boolean],
    "view"
  >;

  muteUser: TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  muted: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  profileRegistry: TypedContractMethod<[], [string], "view">;

  rejectFollowRequest: TypedContractMethod<
    [follower: AddressLike],
    [void],
    "nonpayable"
  >;

  removeFromFollowList: TypedContractMethod<
    [listName: string, user: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestFollow: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  setFollowTier: TypedContractMethod<
    [target: AddressLike, tier: BigNumberish],
    [void],
    "nonpayable"
  >;

  setProfileRegistry: TypedContractMethod<
    [_profileRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unfollow: TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  unmuteUser: TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  userLists: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptFollowRequest"
  ): TypedContractMethod<[follower: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addToFollowList"
  ): TypedContractMethod<
    [listName: string, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "follow"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "followLists"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: string, arg2: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "followRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "followTiers"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "followerCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "followingCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "follows"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFollowList"
  ): TypedContractMethod<[listName: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUserLists"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasFollowRequest"
  ): TypedContractMethod<
    [follower: AddressLike, following: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFollowing"
  ): TypedContractMethod<
    [follower: AddressLike, following: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMuted"
  ): TypedContractMethod<
    [user: AddressLike, mutedUser: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "muteUser"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "muted"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "profileRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rejectFollowRequest"
  ): TypedContractMethod<[follower: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeFromFollowList"
  ): TypedContractMethod<
    [listName: string, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestFollow"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFollowTier"
  ): TypedContractMethod<
    [target: AddressLike, tier: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProfileRegistry"
  ): TypedContractMethod<[_profileRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unfollow"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unmuteUser"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userLists"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "FollowRequestAccepted"
  ): TypedContractEvent<
    FollowRequestAcceptedEvent.InputTuple,
    FollowRequestAcceptedEvent.OutputTuple,
    FollowRequestAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "FollowRequestRejected"
  ): TypedContractEvent<
    FollowRequestRejectedEvent.InputTuple,
    FollowRequestRejectedEvent.OutputTuple,
    FollowRequestRejectedEvent.OutputObject
  >;
  getEvent(
    key: "FollowRequested"
  ): TypedContractEvent<
    FollowRequestedEvent.InputTuple,
    FollowRequestedEvent.OutputTuple,
    FollowRequestedEvent.OutputObject
  >;
  getEvent(
    key: "FollowTierSet"
  ): TypedContractEvent<
    FollowTierSetEvent.InputTuple,
    FollowTierSetEvent.OutputTuple,
    FollowTierSetEvent.OutputObject
  >;
  getEvent(
    key: "Followed"
  ): TypedContractEvent<
    FollowedEvent.InputTuple,
    FollowedEvent.OutputTuple,
    FollowedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Unfollowed"
  ): TypedContractEvent<
    UnfollowedEvent.InputTuple,
    UnfollowedEvent.OutputTuple,
    UnfollowedEvent.OutputObject
  >;
  getEvent(
    key: "UserMuted"
  ): TypedContractEvent<
    UserMutedEvent.InputTuple,
    UserMutedEvent.OutputTuple,
    UserMutedEvent.OutputObject
  >;
  getEvent(
    key: "UserUnmuted"
  ): TypedContractEvent<
    UserUnmutedEvent.InputTuple,
    UserUnmutedEvent.OutputTuple,
    UserUnmutedEvent.OutputObject
  >;

  filters: {
    "FollowRequestAccepted(address,address)": TypedContractEvent<
      FollowRequestAcceptedEvent.InputTuple,
      FollowRequestAcceptedEvent.OutputTuple,
      FollowRequestAcceptedEvent.OutputObject
    >;
    FollowRequestAccepted: TypedContractEvent<
      FollowRequestAcceptedEvent.InputTuple,
      FollowRequestAcceptedEvent.OutputTuple,
      FollowRequestAcceptedEvent.OutputObject
    >;

    "FollowRequestRejected(address,address)": TypedContractEvent<
      FollowRequestRejectedEvent.InputTuple,
      FollowRequestRejectedEvent.OutputTuple,
      FollowRequestRejectedEvent.OutputObject
    >;
    FollowRequestRejected: TypedContractEvent<
      FollowRequestRejectedEvent.InputTuple,
      FollowRequestRejectedEvent.OutputTuple,
      FollowRequestRejectedEvent.OutputObject
    >;

    "FollowRequested(address,address)": TypedContractEvent<
      FollowRequestedEvent.InputTuple,
      FollowRequestedEvent.OutputTuple,
      FollowRequestedEvent.OutputObject
    >;
    FollowRequested: TypedContractEvent<
      FollowRequestedEvent.InputTuple,
      FollowRequestedEvent.OutputTuple,
      FollowRequestedEvent.OutputObject
    >;

    "FollowTierSet(address,address,uint8)": TypedContractEvent<
      FollowTierSetEvent.InputTuple,
      FollowTierSetEvent.OutputTuple,
      FollowTierSetEvent.OutputObject
    >;
    FollowTierSet: TypedContractEvent<
      FollowTierSetEvent.InputTuple,
      FollowTierSetEvent.OutputTuple,
      FollowTierSetEvent.OutputObject
    >;

    "Followed(address,address)": TypedContractEvent<
      FollowedEvent.InputTuple,
      FollowedEvent.OutputTuple,
      FollowedEvent.OutputObject
    >;
    Followed: TypedContractEvent<
      FollowedEvent.InputTuple,
      FollowedEvent.OutputTuple,
      FollowedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Unfollowed(address,address)": TypedContractEvent<
      UnfollowedEvent.InputTuple,
      UnfollowedEvent.OutputTuple,
      UnfollowedEvent.OutputObject
    >;
    Unfollowed: TypedContractEvent<
      UnfollowedEvent.InputTuple,
      UnfollowedEvent.OutputTuple,
      UnfollowedEvent.OutputObject
    >;

    "UserMuted(address,address)": TypedContractEvent<
      UserMutedEvent.InputTuple,
      UserMutedEvent.OutputTuple,
      UserMutedEvent.OutputObject
    >;
    UserMuted: TypedContractEvent<
      UserMutedEvent.InputTuple,
      UserMutedEvent.OutputTuple,
      UserMutedEvent.OutputObject
    >;

    "UserUnmuted(address,address)": TypedContractEvent<
      UserUnmutedEvent.InputTuple,
      UserUnmutedEvent.OutputTuple,
      UserUnmutedEvent.OutputObject
    >;
    UserUnmuted: TypedContractEvent<
      UserUnmutedEvent.InputTuple,
      UserUnmutedEvent.OutputTuple,
      UserUnmutedEvent.OutputObject
    >;
  };
}
